"""add_relationships

Revision ID: 2196d0d082a6
Revises: e2c7c7533c83
Create Date: 2026-06-21 01:36:00.524941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2196d0d082a6'
down_revision: Union[str, Sequence[str], None] = 'e2c7c7533c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_reading_timestamp', 'meter_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reading_timestamp', table_name='meter_readings')
    # ### end Alembic commands ###
