"""add_not_null_constraints

Revision ID: 899a27747f51
Revises: 2196d0d082a6
Create Date: 2026-06-23 01:38:09.827126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '899a27747f51'
down_revision: Union[str, Sequence[str], None] = '2196d0d082a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('load_reports', 'total_load_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('load_reports', 'report_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meter_readings', 'voltage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('meter_readings', 'current',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('meter_readings', 'power_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('meter_readings', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('smart_meters', 'meter_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zones', 'max_capacity_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zones', 'max_capacity_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('smart_meters', 'meter_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meter_readings', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meter_readings', 'power_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('meter_readings', 'current',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('meter_readings', 'voltage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('load_reports', 'report_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('load_reports', 'total_load_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
